# chu ki do chat luong khong khi
cycle_time : 2
# khoang thoi gian chat luong khong khi thay doi
changing_time : 3600
# do bao phu cua xe
cover_radius : 1

num_frame : 4
action_prob : 0.5
action_range : 2

#do dai quang duong
road_length : 400
road_width : 400

#so con duong
road_number : 3
generate_prob : 0.5

#list chieu rong cua tung con duong
road_width_list : [100, 100, 100]
#list chieu trong cua le duong
road_dis_list : [50, 50]

#do giam su chac chan cua khong khi trong vung duoc bao phu
air_discount : 0.2
alpha : 0.25
beta : 0.25
theta : 0.25

n_train_processes : 3
learning_rate: 0.0002
update_interval : 5
gamma : 0.98
max_train_steps : 60000

simulation_time : 1000

batch_size: 
cnn:
  in_channels1: 2
  out_channels1: 64
  kernel_size1: 5

  in_channels2: 64
  out_channels2: 32
  kernel_size2: 3

  in_channels3: 32
  out_channels3: 16
  kernel_size3: 1

  # in_features_fc:
  out_features_fc: 24
  kernel_size_maxpool: 3
  stride_maxpool: 1 
  padding_maxpool: 1

lstm:
  # input_size: 3
  hidden_size: 128
  num_layers: 1